name: advent_2023
description: Solution for Advent of Code 2023
version: 1.0.0

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
